[package]
name = "fingerprinter-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustfft = "6.1"
hound = "3.5"
